name: lexishikhi
description: Bangla-friendly English learning app with coin-based study content.
publish_to: "none"
version: 1.2.1+4

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: 2.5.3
  in_app_purchase: 3.3.0
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  cloud_firestore: ^6.9.0
  google_sign_in: ^7.2.0
  google_mobile_ads: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
